// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgcYzy7MhUw_jCuIPGuv_OQSqbq3W71A',
    appId: '1:1077795804592:web:54fbc66783067953f5b275',
    messagingSenderId: '1077795804592',
    projectId: 'attendance-project-682d7',
    authDomain: 'attendance-project-682d7.firebaseapp.com',
    storageBucket: 'attendance-project-682d7.firebasestorage.app',
    measurementId: 'G-8DC2S0FSFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzkCZIn_FnkceWRf_WspCFasl9hWfu-uk',
    appId: '1:1077795804592:android:a27447974cb89c28f5b275',
    messagingSenderId: '1077795804592',
    projectId: 'attendance-project-682d7',
    storageBucket: 'attendance-project-682d7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCgcYzy7MhUw_jCuIPGuv_OQSqbq3W71A',
    appId: '1:1077795804592:web:7e6255313c4dd903f5b275',
    messagingSenderId: '1077795804592',
    projectId: 'attendance-project-682d7',
    authDomain: 'attendance-project-682d7.firebaseapp.com',
    storageBucket: 'attendance-project-682d7.firebasestorage.app',
    measurementId: 'G-X7D6S3EF4T',
  );
}
